---
title: "Tidy your time series analysis with tsibble"
type: "seminar"
author: "Earo Wang"
date: "31 August, 2018 <br> slides at <http://slides.earo.me/isu18>"
output:
  xaringan::moon_reader:
    css: ["default", "remark.css"]
    self_contained: false
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r initial, echo = FALSE, cache = FALSE, results = 'hide'}
library(knitr)
options(htmltools.dir.version = FALSE, tibble.width = 60, tibble.print_min = 6)
opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, comment = "#>",
  fig.path = 'figure/', cache.path = 'cache/', fig.align = 'center', 
  fig.width = 12, fig.show = 'hold',
  fig.height = 8.5, # 16:9
  # fig.height = 11, # 4:3
  cache = TRUE, external = TRUE, dev = 'svglite'
)
read_chunk('R/theme.R')
```

```{r theme-remark}
```

---

class: inverse middle center

### Slides created via xaringan `r emo::ji("crossed_swords")` <http://slides.earo.me/isu18>

### Open source <https://github.com/earowang/isu18>

### This work is under licensed [`r icon::fa("creative-commons")` BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/).
